name: Build and Test
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.7

      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev

      - name: Build project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_TESTING=ON
          run-build: true

      - name: Test project
        uses: threeal/ctest-action@v1.1.0
