name: Build and Test
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.2.1

      - name: Build project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: |
            MUSEN_BUILD_TESTS=ON
            MUSEN_BUILD_EXAMPLES=ON

      - name: Test project
        uses: threeal/ctest-action@v1.1.0
