# Copyright (c) 2021 ICHIRO ITS
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

name: Build and Test
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: musen

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck libgtest-dev uncrustify
          sudo pip install cpplint

      - name: Create a build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake -DBUILD_TESTING=ON ../musen

      - name: Build the project
        working-directory: build
        run: make -j8

      - name: Test the project
        working-directory: build
        run: ctest --verbose
