# Copyright (c) 2021 ICHIRO ITS
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

name: Deploy Debian Stable
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  deploy-debian-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: musen

      - name: Create a build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake -DCMAKE_INSTALL_PREFIX=/usr ../musen

      - name: Build stable Debian package
        working-directory: build
        run: make -j8 && cpack

      - name: Deploy stable Debian package to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          source: "build/*.deb"
          target: "~/temp/stable/musen/"
          rm: true

      - name: Prepare stable Debian package in the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ~/repository/debian
            reprepro includedeb stable ~/temp/stable/musen/build/*.deb
            rm -rf ~/temp/stable/musen/
