name: Deploy Documentation
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  deploy-documentation:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.2.2

      - name: Install documentation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build documentation
        run: doxygen

      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: doc

      - name: Deploy Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4.0.5
