name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-docs.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Build Documentation
        run: doxygen

      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: doc

      - name: Deploy Documentation
        id: deploy-docs
        uses: actions/deploy-pages@v4.0.5
