# Copyright (c) 2021 ICHIRO ITS
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

name: Deploy Documentation
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  deploy-documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.2
        with:
          path: musen

      - name: Install documentation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Create a build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake ../musen

      - name: Build documentation
        working-directory: build
        run: make doc

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: musen/doc
