name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
jobs:
  test-project:
    name: Test Project
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Build project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: MUSEN_BUILD_TESTS=ON
          run-build: true

      - name: Test project
        uses: threeal/ctest-action@v1.1.0
